#!/usr/bin/env zsh

brew update
brew upgrade
brew cleanup -s
brew cask cleanup

#now diagnostic
brew doctor
brew missing

echo “you can hit mas upgrade to upgrade theses apps from the app store:”
mas outdated
echo “install with: mas upgrade”

#npm update -g
#echo “did you think to launch gem update “
#echo “and pip ? pip freeze — local | grep -v ‘^\-e’ | cut -d = -f 1 | xargs pip install -U “

terminal-notifier -message “All Done! :-)” -title “Up To Date”
