#!/usr/bin/env zsh

brew update
brew upgrade
brew cleanup -s

brew doctor
brew missing

echo "you can hit mas upgrade to upgrade theses apps from the app store:"
mas outdated
echo "install with: mas upgrade"

terminal-notifier -message "All Done!" -title "Up To Date"
